import { type NextPage } from "next";
import Head from "next/head";
import { DashboardBody } from "src/client/components/Dashboard/Body";
import { SearchBody } from "src/client/components/Search/Body";

import DashboardLayout from "src/client/layouts/dashboard";

const Dashboard: NextPage = () => {
	return (
		<DashboardLayout>
			<Head>
				<title>LinkYBase / Collect, organize, and share your links</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <SearchBody />
		</DashboardLayout>
	);
};

export default Dashboard;
