import { type NextPage } from "next";
import Head from "next/head";

import { Button } from "@mantine/core";
import { LandingLayout } from "src/client/layouts/landing";
import { Hero } from "src/client/components/Landing/Hero";

const Home: NextPage = () => {
	return (
		<LandingLayout>
			<Head>
				<title>
					LinkYBase / Collect, organize, and share your links
				</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
		</LandingLayout>
	);
};

export default Home;
