import { type NextPage } from "next";
import Head from "next/head";
import { CollectionBody } from "src/client/components/Collection/LandingBody";

import { LandingLayout } from "src/client/layouts/landing";

const Dashboard: NextPage = () => {
  return (
    <LandingLayout>
      <Head>
        <title>LinkYBase / Collect, organize, and share your links</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CollectionBody />
    </LandingLayout>
  );
};

export default Dashboard;
