import { type NextPage } from "next";
import Head from "next/head";
import { CollectionBody } from "src/client/components/Collection/Body";

import DashboardLayout from "src/client/layouts/dashboard";

const Dashboard: NextPage = () => {
  return (
    <DashboardLayout>
      <Head>
        <title>LinkYBase / Collect, organize, and share your links</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CollectionBody />
    </DashboardLayout>
  );
};

export default Dashboard;
